variables:
  build.version: 2.5.0-ci.$(Build.BuildId)

jobs:
- job: Mac
  pool:
    vmImage: 'macOS-10.13'
  
  steps:
  - task: msbuild@1
    inputs: 
      solution: build/Build.proj
      msbuildArguments: /t:Package /p:BuildVersion=$(build.version)
  
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  
  steps:
  - script: cinst gtksharp -y
  - task: msbuild@1
    inputs: 
      solution: build/Build.proj
      msbuildArguments: /t:Package /p:BuildVersion=$(build.version)
