
jobs:
- job:
  displayName: Mac
  pool:
    vmImage: 'macOS-10.13'
  
  steps:
  - script: ./build.sh
  
- job:
  displayName: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  
  steps:
  - task: msbuild@1
    inputs: 
      solution: build/Build.proj
      msbuildArguments: /t:Package /p:BuildVersion=2.5.0-ci.$(BuildID)
