variables:
  build.version: 2.5.0-ci.$(Build.BuildId)
  build.configuration: Release
  build.arguments: /t:Package /p:Configuration=$(build.configuration) /p:BuildVersion=$(build.version)

jobs:
- job: Mac
  pool:
    vmImage: 'macOS-10.13'
  
  steps:
  - task: msbuild@1
    inputs: 
      solution: build/Build.proj
      msbuildArguments: $(build.arguments)
  - task: CopyFiles@2
    inputs:
      contents: artifacts\nuget\$(build.configuration)\Eto.Platform.XamMac*.nupkg
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  
  steps:
  - script: cinst gtksharp -y
  - task: msbuild@1
    inputs: 
      solution: build/Build.proj
      msbuildArguments: $(build.arguments)
  - task: CopyFiles@2
    inputs:
      contents: artifacts\nuget\$(build.configuration)\*.nupkg
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
